import {StyleSheet, Platform, Dimensions} from 'react-native';
const width = Dimensions.get('window').width;
export const homePageStyles = StyleSheet.create({
  userInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    //justifyContent: 'space-between',
    backgroundColor: '#1b97d3',
    borderBottomWidth: 3,
    borderStyle: 'solid',
    borderBottomColor: '#1789bb',
    padding: 10,
    paddingTop: (Platform.OS === 'ios') ? 34 : 10,
  },
  imageWrapper: {
    backgroundColor: 'white',
    borderWidth: 1,
    // borderStyle: 'solid',
    borderColor: 'white',
    borderRadius: (Platform.OS === "android") ? 48 : 48,
    height: (Platform.OS === "android") ? 96 : 96,
    width: (Platform.OS === "android") ? 96 : 96,
    marginRight: 10,
    // marginTop: (Platform.OS === "android") ? 0 : 24,
  },
  image: {
    height: (Platform.OS === "android") ? 94 : 94,
    width: (Platform.OS === "android") ? 94 : 94,
    borderRadius: (Platform.OS === "android") ? 94 : 47,
    zIndex: 0,
  },
  nameText: {
    color: 'white',
    fontSize: (Platform.OS === "android") ? 19 : 14,
    //fontWeight: '500',
    width: width / 3,
    textAlign: 'left',
  },
  locationText: {
    color: '#b3cee9',
    fontSize: 14,
    fontWeight: '400',
    width: width / 3,
  },
  separator: {
    ///flex: 1,
    //backgroundColor: 'red',
    borderBottomWidth: 0.3,
    marginTop: 4,
    marginBottom: 6,
    borderColor: 'rgba(255,255,255,0.24)',
  },
  levelDisplay: {
    // backgroundColor: 'red',
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  levelText: {
    //flex: 1,
    color: 'white',
    //backgroundColor: 'red',
    height: 20,
    fontSize: (Platform.OS === "android") ? 17 : 12,
    //fontWeight: '500',
    //width: width / 15,
    textAlign: 'left',
  },
  levelPercent: {
    color: '#b3cee9',
    //backgroundColor: 'red',
    height: 20,
    //flex: 1,
    fontSize: (Platform.OS === "android") ? 17 : 12,
    //fontWeight: '500',
    //width: width / 20,
    textAlign: 'right',
    zIndex: 0,
  },
  practiceButton: {
    // position: 'absolute',
    // right: 10,
    // top: 50,
    width: width / 4,
    // height: 40,
    borderStyle: 'solid',
    borderWidth: 1,
    borderColor: 'white',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 5
  },
  practiceButtonText: {
    color: 'white',
    fontSize: (width === 320) ? 14 : 16,
    fontWeight: (Platform.OS === "android") ? '500' : '400',
    textAlign: 'center',
    paddingVertical: 5,
  }
});
